// CLI agents (`pi-agent`, see cli/pi-agent.mjs + docs/pi-agent-cli-plan.md).
//
// Agents run as their own `pi --mode rpc` processes owned by the CLI, never by
// this app. The app only observes:
// - Registry: JSON records under $PI_AGENT_HOME (default
//   ~/.pi/agent/pi-tauri-ui/agents), read on demand — no polling.
// - Live bridge (Unix only): a socket at <home>/ui.sock. Each CLI runner
//   connects, sends `agent_update` records and its pi events (already tagged
//   with cwd + session, exactly like the pool's own events), and accepts
//   `abort` / `ui_response` back. Events are re-emitted as `pi-event`, so the
//   frontend's existing routing (spinner, finished dot, live transcript) works
//   unchanged.
//
// One writer per session file: when an agent settles, any pool process the
// app holds on that session (opened read-only while the agent ran) is retired
// BEFORE the settle is forwarded, so the next read loads the finished file.

use std::{path::{Path, PathBuf}, process::Stdio, sync::Arc};

use serde_json::Value;
use tauri::AppHandle;
#[cfg(unix)]
use tauri::Emitter;
use tokio::sync::mpsc;

use crate::{retire, Instance, Pool};

pub const DEFAULT_MODEL: &str = "opencode-go/muse-spark-1.3-contributor";
pub const DEFAULT_MAX_CONCURRENT: u64 = 12;
const LIST_LIMIT: usize = 100;

/// Same root the CLI uses: $PI_AGENT_HOME, else ~/.pi/agent/pi-tauri-ui.
pub fn agent_home() -> Option<PathBuf> {
    if let Some(h) = std::env::var_os("PI_AGENT_HOME") {
        if !h.is_empty() {
            return Some(PathBuf::from(h));
        }
    }
    dirs::home_dir().map(|h| h.join(".pi").join("agent").join("pi-tauri-ui"))
}

pub fn is_terminal(status: &str) -> bool {
    matches!(status, "done" | "failed" | "cancelled" | "lost")
}

/// Agent ids are generated by the CLI (`ag-YYYYMMDD-HHMMSS-xxxx`); anything
/// else never touches the filesystem.
pub fn valid_id(id: &str) -> bool {
    !id.is_empty() && id.len() <= 64 && id.chars().all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_' || c == '.') && !id.contains("..")
}

fn pid_alive(pid: i64) -> bool {
    if pid <= 0 {
        return false;
    }
    std::process::Command::new("kill")
        .arg("-0")
        .arg(pid.to_string())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// Pure (unit-tested): a record whose runner died without finishing reads
/// as `lost`; malformed records are dropped.
pub fn normalize_record(mut v: Value, alive: &dyn Fn(i64) -> bool) -> Option<Value> {
    v.get("id").and_then(Value::as_str)?;
    let status = v.get("status").and_then(Value::as_str).unwrap_or("").to_string();
    if !is_terminal(&status) {
        let pid = v.get("pid").and_then(Value::as_i64).unwrap_or(0);
        if !alive(pid) {
            v["status"] = Value::String("lost".into());
        }
    }
    Some(v)
}

/// Registry records, newest first (capped).
pub fn list_agents_in(home: &Path, alive: &dyn Fn(i64) -> bool) -> Vec<Value> {
    let mut out: Vec<Value> = Vec::new();
    let Ok(entries) = std::fs::read_dir(home.join("agents")) else { return out };
    for e in entries.flatten() {
        let p = e.path();
        if p.extension().and_then(|x| x.to_str()) != Some("json") {
            continue;
        }
        let Ok(text) = std::fs::read_to_string(&p) else { continue };
        let Ok(v) = serde_json::from_str::<Value>(&text) else { continue };
        if let Some(v) = normalize_record(v, alive) {
            out.push(v);
        }
    }
    out.sort_by_key(|v| std::cmp::Reverse(v.get("createdAt").and_then(Value::as_u64).unwrap_or(0)));
    out.truncate(LIST_LIMIT);
    out
}

/// Recommended models + config, falling back to the CLI's seed values.
pub fn models_in(home: &Path) -> Value {
    let models = std::fs::read_to_string(home.join("models.json"))
        .ok()
        .and_then(|t| serde_json::from_str::<Value>(&t).ok())
        .filter(|v| v.get("models").map(Value::is_array).unwrap_or(false))
        .unwrap_or_else(|| {
            serde_json::json!({
                "default": DEFAULT_MODEL,
                "models": [{
                    "id": DEFAULT_MODEL,
                    "use": "Default for delegated coding work: reading code, scoped edits, running tests, and reporting back. Cheap and fast enough to run many agents in parallel.",
                    "avoid": "Skip it for ambiguous architecture or product calls, or long open-ended investigations where a stronger reasoning model is worth the cost."
                }]
            })
        });
    let max = std::fs::read_to_string(home.join("config.json"))
        .ok()
        .and_then(|t| serde_json::from_str::<Value>(&t).ok())
        .and_then(|c| c.get("maxConcurrent").and_then(Value::as_u64))
        .filter(|n| *n >= 1)
        .unwrap_or(DEFAULT_MAX_CONCURRENT);
    serde_json::json!({
        "default": models.get("default").cloned().unwrap_or(Value::String(DEFAULT_MODEL.into())),
        "models": models.get("models").cloned().unwrap_or(Value::Array(vec![])),
        "maxConcurrent": max,
    })
}

fn home_or_err() -> Result<PathBuf, String> {
    agent_home().ok_or_else(|| "no home folder".to_string())
}

#[tauri::command]
pub async fn pi_agents_list() -> Result<Value, String> {
    let home = home_or_err()?;
    tokio::task::spawn_blocking(move || {
        let agents = list_agents_in(&home, &pid_alive);
        let count = |s: &str| agents.iter().filter(|a| a.get("status").and_then(Value::as_str) == Some(s)).count();
        let (running, queued) = (count("running"), count("queued"));
        let max = models_in(&home).get("maxConcurrent").cloned().unwrap_or(Value::from(DEFAULT_MAX_CONCURRENT));
        serde_json::json!({ "agents": agents, "running": running, "queued": queued, "maxConcurrent": max })
    })
    .await
    .map_err(|e| e.to_string())
}

#[tauri::command]
pub async fn pi_agent_models() -> Result<Value, String> {
    let home = home_or_err()?;
    tokio::task::spawn_blocking(move || models_in(&home)).await.map_err(|e| e.to_string())
}

/// Stop a queued or running agent: SIGTERM to its CLI runner, which aborts
/// pi cleanly and records `cancelled`.
#[tauri::command]
pub async fn pi_agent_cancel(id: String) -> Result<Value, String> {
    if !valid_id(&id) {
        return Err("invalid agent id".into());
    }
    let home = home_or_err()?;
    let text = std::fs::read_to_string(home.join("agents").join(format!("{}.json", id))).map_err(|_| format!("no agent {}", id))?;
    let rec: Value = serde_json::from_str(&text).map_err(|_| "unreadable agent record".to_string())?;
    let status = rec.get("status").and_then(Value::as_str).unwrap_or("");
    if is_terminal(status) {
        return Ok(serde_json::json!({ "ok": true, "status": status }));
    }
    let pid = rec.get("pid").and_then(Value::as_i64).unwrap_or(0);
    if pid <= 0 || !pid_alive(pid) {
        return Err("that agent's runner is no longer running".into());
    }
    let ok = tokio::process::Command::new("kill")
        .arg("-TERM")
        .arg(pid.to_string())
        .status()
        .await
        .map(|s| s.success())
        .unwrap_or(false);
    if !ok {
        return Err("couldn't signal the agent".into());
    }
    Ok(serde_json::json!({ "ok": true }))
}

/// Remove finished records (and their saved answers).
#[tauri::command]
pub async fn pi_agents_clear() -> Result<Value, String> {
    let home = home_or_err()?;
    tokio::task::spawn_blocking(move || {
        let mut removed = 0u64;
        for a in list_agents_in(&home, &pid_alive) {
            let status = a.get("status").and_then(Value::as_str).unwrap_or("");
            let Some(id) = a.get("id").and_then(Value::as_str) else { continue };
            if !is_terminal(status) || !valid_id(id) {
                continue;
            }
            if std::fs::remove_file(home.join("agents").join(format!("{}.json", id))).is_ok() {
                removed += 1;
            }
            let _ = std::fs::remove_file(home.join("agents").join(format!("{}.out.md", id)));
        }
        serde_json::json!({ "removed": removed })
    })
    .await
    .map_err(|e| e.to_string())
}

/// Pure (unit-tested): message records from a pi session file (JSONL),
/// oldest first. Used for the read-only view of a running agent's chat, so
/// the app never spawns a second pi process on a session the CLI is writing.
pub fn session_messages(text: &str) -> Vec<Value> {
    text.lines()
        .filter_map(|l| serde_json::from_str::<Value>(l).ok())
        .filter(|v| v.get("type").and_then(Value::as_str) == Some("message"))
        .filter_map(|v| v.get("message").cloned())
        .collect()
}

/// Read a running agent's transcript straight from its session file. Only
/// session files named by an agent record are readable (allowlist).
#[tauri::command]
pub async fn pi_read_session(path: String) -> Result<Value, String> {
    let home = home_or_err()?;
    tokio::task::spawn_blocking(move || {
        let known = list_agents_in(&home, &|_| true)
            .iter()
            .any(|a| a.get("sessionFile").and_then(Value::as_str) == Some(path.as_str()));
        if !known || !path.ends_with(".jsonl") {
            return Err("not an agent session".to_string());
        }
        let text = std::fs::read_to_string(&path).map_err(|e| format!("couldn't read the agent's session: {}", e))?;
        Ok(serde_json::json!({ "messages": session_messages(&text) }))
    })
    .await
    .map_err(|e| e.to_string())?
}

/// The CLI runner holding a session, if it is connected over the socket.
pub async fn link_for(pool: &Arc<Pool>, session: Option<&str>) -> Option<mpsc::UnboundedSender<String>> {
    let s = session?;
    pool.agent_links.lock().await.get(s).cloned()
}

/// Retire every pool process holding `session` (a stale read-only snapshot).
async fn retire_holders(pool: &Arc<Pool>, session: &str) {
    let insts: Vec<Arc<Instance>> = pool.instances.lock().await.values().cloned().collect();
    for inst in insts {
        let held = inst.session_file.lock().await.clone();
        if held.as_deref() == Some(session) {
            retire(pool, &inst).await;
        }
    }
}

#[cfg(unix)]
pub fn start_bridge(app: AppHandle, pool: Arc<Pool>) {
    tauri::async_runtime::spawn(async move {
        let Some(home) = agent_home() else { return };
        if std::fs::create_dir_all(&home).is_err() {
            return;
        }
        let sock = home.join("ui.sock");
        // Another running copy of the app owns the socket: leave it alone.
        if tokio::net::UnixStream::connect(&sock).await.is_ok() {
            return;
        }
        let _ = std::fs::remove_file(&sock);
        let listener = match tokio::net::UnixListener::bind(&sock) {
            Ok(l) => l,
            Err(_) => return,
        };
        loop {
            match listener.accept().await {
                Ok((stream, _)) => {
                    let app = app.clone();
                    let pool = pool.clone();
                    tauri::async_runtime::spawn(async move { handle_conn(app, pool, stream).await });
                }
                Err(_) => tokio::time::sleep(std::time::Duration::from_millis(250)).await,
            }
        }
    });
}

#[cfg(not(unix))]
pub fn start_bridge(_app: AppHandle, _pool: Arc<Pool>) {}

#[cfg(unix)]
async fn handle_conn(app: AppHandle, pool: Arc<Pool>, stream: tokio::net::UnixStream) {
    use tokio::io::{AsyncBufReadExt, AsyncWriteExt, BufReader};
    let (rd, mut wr) = stream.into_split();
    let (tx, mut rx) = mpsc::unbounded_channel::<String>();
    // Writer ends on its own once every sender (this fn + route map) is gone.
    tauri::async_runtime::spawn(async move {
        while let Some(line) = rx.recv().await {
            if wr.write_all(line.as_bytes()).await.is_err() || wr.write_all(b"\n").await.is_err() {
                break;
            }
        }
    });
    let mut reader = BufReader::new(rd);
    let mut buf: Vec<u8> = Vec::with_capacity(16 * 1024);
    let mut owned: Vec<String> = Vec::new();
    loop {
        buf.clear();
        match reader.read_until(b'\n', &mut buf).await {
            Ok(0) | Err(_) => break,
            Ok(_) => {}
        }
        while buf.last() == Some(&b'\n') || buf.last() == Some(&b'\r') {
            buf.pop();
        }
        if buf.is_empty() {
            continue;
        }
        let Ok(msg) = serde_json::from_slice::<Value>(&buf) else { continue };
        match msg.get("type").and_then(Value::as_str) {
            Some("agent_update") => {
                let Some(agent) = msg.get("agent").cloned() else { continue };
                let status = agent.get("status").and_then(Value::as_str).unwrap_or("").to_string();
                if let Some(s) = agent.get("sessionFile").and_then(Value::as_str) {
                    if is_terminal(&status) {
                        pool.agent_links.lock().await.remove(s);
                        retire_holders(&pool, s).await;
                    } else {
                        pool.agent_links.lock().await.insert(s.to_string(), tx.clone());
                        if !owned.iter().any(|o| o == s) {
                            owned.push(s.to_string());
                        }
                    }
                }
                let _ = app.emit("pi-event", serde_json::json!({ "type": "agent_update", "agent": agent }));
            }
            Some("event") => {
                let Some(mut ev) = msg.get("event").cloned() else { continue };
                if let Some(s) = ev.get("session").and_then(Value::as_str).map(String::from) {
                    if ev.get("type").and_then(Value::as_str) == Some("agent_settled") {
                        retire_holders(&pool, &s).await;
                    }
                    if !owned.iter().any(|o| o == &s) {
                        pool.agent_links.lock().await.insert(s.clone(), tx.clone());
                        owned.push(s);
                    }
                }
                if let Value::Object(map) = &mut ev {
                    map.insert("external".to_string(), Value::Bool(true));
                }
                let _ = app.emit("pi-event", ev);
            }
            _ => {}
        }
    }
    let mut links = pool.agent_links.lock().await;
    for s in &owned {
        links.remove(s);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dead_runners_read_as_lost_and_finished_records_stay() {
        let dead = |_: i64| false;
        let alive = |_: i64| true;
        let running = serde_json::json!({"id": "a", "status": "running", "pid": 42});
        assert_eq!(normalize_record(running.clone(), &dead).unwrap()["status"], "lost");
        assert_eq!(normalize_record(running, &alive).unwrap()["status"], "running");
        let done = serde_json::json!({"id": "b", "status": "done", "pid": 42});
        assert_eq!(normalize_record(done, &dead).unwrap()["status"], "done");
        assert!(normalize_record(serde_json::json!({"status": "done"}), &alive).is_none());
    }

    #[test]
    fn ids_are_validated_before_touching_files() {
        assert!(valid_id("ag-20261002-101500-ab12"));
        assert!(!valid_id("../etc/passwd"));
        assert!(!valid_id("a/b"));
        assert!(!valid_id(""));
        assert!(!valid_id(".."));
    }

    #[test]
    fn registry_lists_newest_first_and_models_fall_back_to_seed() {
        let home = std::env::temp_dir().join(format!("pi-ui-agents-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(home.join("agents")).unwrap();
        for (id, at) in [("old", 1), ("new", 3), ("mid", 2)] {
            std::fs::write(home.join("agents").join(format!("{}.json", id)), format!("{{\"id\":\"{}\",\"status\":\"done\",\"createdAt\":{}}}", id, at)).unwrap();
        }
        std::fs::write(home.join("agents").join("new.out.md"), "answer").unwrap();
        std::fs::write(home.join("agents").join("junk.json"), "not json").unwrap();
        let list = list_agents_in(&home, &|_| true);
        let ids: Vec<&str> = list.iter().map(|v| v["id"].as_str().unwrap()).collect();
        assert_eq!(ids, vec!["new", "mid", "old"]);
        let m = models_in(&home);
        assert_eq!(m["default"], DEFAULT_MODEL);
        assert_eq!(m["maxConcurrent"], 12);
        std::fs::write(home.join("config.json"), "{\"maxConcurrent\":3}").unwrap();
        std::fs::write(home.join("models.json"), "{\"default\":\"a/b\",\"models\":[{\"id\":\"a/b\",\"use\":\"u\",\"avoid\":\"v\"}]}").unwrap();
        let m = models_in(&home);
        assert_eq!(m["default"], "a/b");
        assert_eq!(m["maxConcurrent"], 3);
        std::fs::remove_dir_all(home).unwrap();
    }

    #[test]
    fn session_file_yields_messages_only() {
        let text = "{\"type\":\"session\",\"cwd\":\"/p\"}\n{\"type\":\"message\",\"message\":{\"role\":\"user\",\"content\":\"hi\"}}\nnot json\n{\"type\":\"model_change\"}\n{\"type\":\"message\",\"message\":{\"role\":\"assistant\",\"content\":[]}}\n";
        let m = session_messages(text);
        assert_eq!(m.len(), 2);
        assert_eq!(m[0]["role"], "user");
        assert_eq!(m[1]["role"], "assistant");
    }

    #[test]
    fn terminal_statuses() {
        for s in ["done", "failed", "cancelled", "lost"] {
            assert!(is_terminal(s));
        }
        for s in ["queued", "running", ""] {
            assert!(!is_terminal(s));
        }
    }
}
